name: Setup Backend
description: Setup Python with requirements (no component)

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.11'
  streamlit-version:
    description: 'Streamlit version to use'
    required: true
    default: '1.31'

runs:
  using: composite
  steps:

  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}

  - name: Display Python version
    shell: bash --login -eo pipefail {0}
    run: python -c "import sys; print(sys.version)"

  - name: Install Streamlit
    run: |
      if [[ ${{ inputs.streamlit-version }} == 'latest' ]]; then
        pip install streamlit
      else
        pip install streamlit==${{ inputs.streamlit-version }}
      fi
    shell: bash --login -eo pipefail {0}

  - run: pip install -e ".[dev,tests]"
    shell: bash --login -eo pipefail {0}

  - run: pip uninstall streamlit-searchbox -y
    shell: bash --login -eo pipefail {0}
