name: Setup Backend (with uv)
description: Setup Python with uv (no component)

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.12'
  streamlit-version:
    description: 'Streamlit version to use'
    required: true
    default: '1.36'

runs:
  using: composite
  steps:

  - name: Install uv
    uses: astral-sh/setup-uv@v7

  - name: Sync dependencies
    run: uv sync
    shell: bash

  - name: Install Python ${{ inputs.python-version }} with uv
    run: uv python install ${{ inputs.python-version }}
    shell: bash

  - name: Pin Python version inside project
    run: uv python pin ${{ inputs.python-version }}
    shell: bash

  - name: Display Python version
    run: uv run python -c "import sys; print(sys.version)"
    shell: bash

  - name: Install Streamlit
    run: |
      if [[ ${{ inputs.streamlit-version }} == 'latest' ]]; then
        uv add --dev streamlit
      else
        uv add --dev streamlit==${{ inputs.streamlit-version }}
      fi
    shell: bash

  - name: Confirm imports
    run: uv run python -c "import streamlit_searchbox"
    shell: bash
