name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: streamlit_searchbox/frontend/package-lock.json

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install -e ".[dev,tests]"
      - run: pip uninstall streamlit-searchbox -y

      - run: playwright install

      - run: npm install --force
        working-directory: ./streamlit_searchbox/frontend

      - run: npm run build
        working-directory: ./streamlit_searchbox/frontend

      - run: python -m pytest tests/

      - run: python -m pytest tests/playwright.py --verbose
